### ISSUE TITLE
Add contributors list to app

### ISSUE THREAD

**Issue by jeroenleenarts** [CocoaHeadsNL/CocoaHeadsNL-iOS#2]
We hope this app to be build with the help of our community.

Having a list of those who contributed to the app in the app would be great. (Consider it to be a badge of honor.) Github provides API to get the info:

curl https://api.github.com/repos/CocoaHeadsNL/CocoaHeadsNL-iOS/stats/contributors
curl https://api.github.com/users/:username

Both are unthrottled open API's one can call. Considering that the app would be used geographically dispersed we could perfectly well call these API's on demand when a users open a screen in the app meant to contain this info.

Extra bonus for loading a users gravatar image with their pretty formatted name.
The list should be a ranked list with the person with the most contributions at the top. On which specific items we would be sorting on we would have to have a discussion.

Also how to reach this screen we would have to discuss. Contributions list is something I would consider to be part of an "About" type screen.

**Comment by jeroenleenarts** [comment]
We already sync the data from github.

See:

``` bash
curl -X GET \
  -H "X-Parse-Application-Id: PJhojEKv3qnrcSM6uwPb8KaQbyiG0ruFnFV33FHD" \
  -H "X-Parse-REST-API-Key: HMS54ic8V70F6zX6chCRFpXB7vzeZmdqsPxddLb7" \
  https://api.parse.com/1/classes/Contributor
```

**Comment by jeroenleenarts** [comment]
#28

**Comment by barthoffman** [comment]
Added Tab shows contributors in collectionView with small text.
