### ISSUE TITLE
Add an endless scrollview to the top collectionView on companiesViewController

### ISSUE THREAD

**Issue by barthoffman** [CocoaHeadsNL/CocoaHeadsNL-iOS#26]
The idea is to create the illusion of an endless scroll in both directions just like for instance in the discover tab on the App Store. 
A possible way is to add duplicate objects at the end and start of the scrollview and turn off animations when you hit the index in scrollViewDidEndAccelerating. But any nicer ways are welcome :)

**Comment by bschotanus** [comment]
A description of this approach can be found at: http://adoptioncurve.net/archives/2013/07/building-a-circular-gallery-with-a-uicollectionview/

**Comment by jeroenleenarts** [comment]
@barthoffman Is the ordering on proximity done from left to right? Left being nearest? If so, what would a wrap around scroll get us?

**Comment by barthoffman** [comment]
@jeroenleenarts That's the second CollectionView and yes you're correct. The continues scrollview is for the collectionView on top :)
