### ISSUE TITLE
Remove REALM, start using CoreData

### ISSUE THREAD

**Issue by jeroenleenarts** [CocoaHeadsNL/CocoaHeadsNL-iOS#50]

**Comment by SpacyRicochet** [comment]
Do we really need Core Data? Have we considered just keeping everything in memory instead? If you combine that with proper view reusing, we shouldn't even have to notice the lack of cache.

**Comment by jeroenleenarts** [comment]
We added local storage to make sure we have something to show due to slowness of CloudKit.

**Comment by jeroenleenarts** [comment]
yay!

**Comment by Heufiih** [comment]
Hi
